Description: >
  This template deploys an Elastic Container Registry (ECR) that will host all docker
  images for the application.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  ContainerECR: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${EnvironmentName}-ecr

Outputs:
  ContainerEcrArn:
    Value: !GetAtt ContainerECR.Arn