AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template deploys an Elastic Container Registry (ECR) that will host all docker
  images for the application.

Parameters:
  BackendEcrName:
    Description: "Name of backend ECR"
    Type: String
    AllowedPattern: ".+" # Required Parameter
    ConstraintDescription: "Backend ECR name is required."

  FrontendEcrName:
    Description: "Name of frontend ECR"
    Type: String
    AllowedPattern: ".+" # Required Parameter
    ConstraintDescription: "Frontend ECR name is required."

  GatewayEcrName:
    Description: "Name of API gateway ECR"
    Type: String
    AllowedPattern: ".+" # Required Parameter
    ConstraintDescription: "API gateway ECR name is required."

Resources:
  BackendEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BackendEcrName

  FrontendEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref FrontendEcrName

  GatewayEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref GatewayEcrName

Outputs:
  BackendEcrName:
    Value: !Ref BackendEcr
    Description: "Name of backend ECR"
    Export:
      Name: "BackendEcrName"

  FrontendEcrName:
    Value: !Ref FrontendEcr
    Description: "Name of frontend ECR"
    Export:
      Name: "FrontendEcrName"

  GatewayEcrName:
    Value: !Ref GatewayEcr
    Description: "Name of API Gateway ECR"
    Export:
      Name: "GatewayEcrName"
